CLASS_NAMES = [
    "cat - abyssinian",
    "cat - american shorthair",
    "cat - bengal",
    "cat - birman",
    "cat - bombay",
    "cat - british shorthair",
    "cat - egyptian mau",
    "cat - maine coon",
    "cat - persian",
    "cat - ragdoll",
    "cat - russian blue",
    "cat - scottishfold",
    "cat - siamese",
    "cat - sphinx",
    "cat - sphynx",

    "dog - afghan",
    "dog - african wild dog",
    "dog - airedale",
    "dog - akita",
    "dog - american hairless",
    "dog - american spaniel",
    "dog - aspin",
    "dog - basenji",
    "dog - basset",
    "dog - beagle",
    "dog - bearded collie",
    "dog - bermaise",
    "dog - bernard-dog - saint",
    "dog - bernese mountain",
    "dog - bichon frise",
    "dog - blenheim",
    "dog - bloodhound",
    "dog - bluetick",
    "dog - border collie",
    "dog - border-dog - collie",
    "dog - borzoi",
    "dog - boston terrier",
    "dog - boxer",
    "dog - bull mastiff",
    "dog - bull terrier",
    "dog - bulldog",
    "dog - bulldong-dog - french",
    "dog - cairn",
    "dog - cavalier-dog - charles-dog - king-dog - spaniel",
    "dog - chihuahua",
    "dog - chinese crested",
    "dog - chow",
    "dog - clumber",
    "dog - coated-dog - flat-dog - retriever",
    "dog - cockapoo",
    "dog - cocker",
    "dog - collie",
    "dog - corgi",
    "dog - coyote",
    "dog - dachshund",
    "dog - dalmatian",
    "dog - dhole",
    "dog - dingo",
    "dog - doberman",
    "dog - doberman-dog - pinscher",
    "dog - elk hound",
    "dog - french bulldog",
    "dog - german sheperd",
    "dog - german-dog - sheperd",
    "dog - golden retriever",
    "dog - golden-dog - retriever",
    "dog - great dane",
    "dog - great perenees",
    "dog - greyhound",
    "dog - groenendael",
    "dog - havanese",
    "dog - husky-dog - siberian",
    "dog - irish spaniel",
    "dog - irish wolfhound",
    "dog - japanese spaniel",
    "dog - komondor",
    "dog - labradoodle",
    "dog - labrador",
    "dog - labrador-dog - retriever",
    "dog - lhasa",
    "dog - malinois",
    "dog - maltese",
    "dog - mex hairless",
    "dog - miniature-dog - schnauzer",
    "dog - newfoundland",
    "dog - pekinese",
    "dog - pit bull",
    "dog - pomeranian",
    "dog - poodle",
    "dog - pug",
    "dog - rhodesian",
    "dog - rottweiler",
    "dog - saint bernard",
    "dog - schnauzer",
    "dog - scotch terrier",
    "dog - shar pei",
    "dog - sheepdog-dog - shetland",
    "dog - shiba inu",
    "dog - shih-dog - tzu",
    "dog - shih-tzu",
    "dog - siberian husky",
    "dog - vizsla",
    "dog - yorkie"
]
